### ISSUE TITLE
Fix empty tag value OR queries

### ISSUE THREAD

**Issue by evanh** [getsentry/snuba-sdk#185]
When there are conditions like `x='a' OR x='b' OR x=''` it can cause Clickhouse errors. Replace conditions like this with `x IN ['a', 'b', '']`.

This happens in both SnQL queries and MQL queries.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/snuba-sdk/pull/183
- [ ] https://github.com/getsentry/sentry/pull/68655
```

**Comment by mcannizz** [comment]
@kylemumma it looks like this work is done, so I'm going to close this issue. Please reopen and let me know if I'm missing something.
